// Segmentové formuláře podle zadávací dokumentace §8.
// Skórovaná pole (scored:true) jsou strukturovaná a synchronizují se zpět do Raynetu.

import type { SegmentDef } from "../types.js";

const SPOKOJENOST = [
  { value: "1", label: "1 — velmi nespokojen" },
  { value: "2", label: "2 — spíše nespokojen" },
  { value: "3", label: "3 — neutrální" },
  { value: "4", label: "4 — spíše spokojen" },
  { value: "5", label: "5 — velmi spokojen" },
];

const ANO_NE = [
  { value: "ano", label: "Ano" },
  { value: "ne", label: "Ne" },
];

const ZAJEM = [
  { value: "zadny", label: "Žádný" },
  { value: "nizky", label: "Nízký" },
  { value: "stredni", label: "Střední" },
  { value: "vysoky", label: "Vysoký" },
];

export const SEGMENTS: SegmentDef[] = [
  // 8.1 — Vodárny, obce, teplárny
  {
    key: "vodarny",
    label: "Vodárny, obce, teplárny",
    short: "Vodárny / obce / teplárny",
    description: "Segment veřejných a komunálních zákazníků s odběrnými místy a tendry.",
    fields: [
      {
        key: "typ_zakaznika",
        label: "Typ zákazníka",
        type: "select",
        required: true,
        reportable: true,
        help: "Umožní členění uvnitř segmentu.",
        options: [
          { value: "vodarna", label: "Vodárna" },
          { value: "obec", label: "Obec" },
          { value: "teplarna", label: "Teplárna" },
        ],
      },
      {
        key: "pocet_odbernych_mist",
        label: "Počet odběrných míst",
        type: "number",
        required: true,
        reportable: true,
        prefillFromRaynet: "pocet_odbernych_mist",
        help: "Klíčové pro velikost zákazníka; předvyplní se z Raynetu, pokud tam existuje.",
      },
      {
        key: "meridla_pouzivana",
        label: "Měřidla, která aktuálně používají",
        type: "multiselect",
        required: true,
        codebook: "znacky_meridel",
        multi: true,
        allowOther: true,
        reportable: true,
        help: "Vyber značky z nabídky; pro neobvyklé použij „Jiné“ a dopiš ručně.",
      },
      {
        key: "obvykla_stavebni_delka",
        label: "Nejčastější stavební délka měřidel",
        type: "multiselect",
        required: false,
        codebook: "stavebni_delky",
        multi: true,
        allowOther: true,
        reportable: true,
        help: "Přednastavené délky; pro jinou použij „Jiné“.",
      },
      {
        key: "zkusebna",
        label: "Zkušebna, se kterou spolupracují",
        type: "radio",
        required: true,
        codebook: "zkusebny",
        allowOther: true,
        reportable: true,
        help: "Vyber zkušebnu; pokud chybí, použij „Jiné“. Číselník spravuje admin.",
      },
      {
        key: "spokojenost_dodavatele",
        label: "Spokojenost s aktuálním dodavatelem",
        type: "scale",
        required: false,
        scored: true,
        reportable: true,
        options: SPOKOJENOST,
        help: "Slovní hodnocení 1–5. Vstup do skóringu (write-back do Raynetu).",
      },
      {
        key: "cena_dodavatele",
        label: "Ceny aktuálního dodavatele",
        type: "text",
        required: false,
        help: "Podklad pro obchodní argumentaci.",
      },
      {
        key: "co_je_trapi",
        label: "Co je trápí, co potřebují řešit",
        type: "textarea",
        required: true,
        help: "Klíčové pole pro další obchodní postup.",
      },
      {
        key: "informacni_software",
        label: "Jaký informační software používají",
        type: "tags",
        required: true,
        codebook: "software",
        multi: true,
        learn: true,
        scored: true,
        reportable: true,
        help: "Vpisuj volně jako tagy — vyber z dříve použitých, nebo napiš nový (uloží se pro příště). Vstup do skóringu.",
      },
      {
        key: "zajem_dalkove_odecty",
        label: "Povědomí a zájem o dálkové odečty",
        type: "scale",
        required: true,
        scored: true,
        reportable: true,
        options: ZAJEM,
        help: "Normalizovaná úroveň zájmu; vstup do skóringu (write-back).",
      },
      {
        key: "zajem_dalkove_odecty_detail",
        label: "Zájem o dálkové odečty — podrobnosti",
        type: "textarea",
        required: false,
        help: "Rozepiš kontext: konkrétní potřeby, termíny, kdo rozhoduje, co je brzdí. Důležité pro další postup.",
      },
      {
        key: "termin_tendru",
        label: "Termín nejbližšího poptávkového řízení nebo tendru",
        type: "date",
        required: true,
        reportable: true,
        help: "Musí být filtrovatelné podle období (blížící se tendry).",
      },
      {
        key: "specifikace_tendru",
        label: "Specifikace tendru",
        type: "textarea",
        required: false,
        help: "Co budou poptávat a podle čeho hodnotit.",
      },
      {
        key: "bytovy_sektor",
        label: "Možnost spolupráce na bytovém sektoru",
        type: "radio",
        required: false,
        options: ANO_NE,
        reportable: true,
        help: "Je u zákazníka potenciál i v bytovém sektoru?",
      },
    ],
  },

  // 8.2 — Správce
  {
    key: "spravce",
    label: "Správce",
    short: "Správce nemovitostí",
    description: "Správcovské společnosti s portfoliem spravovaných bytů a výměnami měřidel.",
    fields: [
      {
        key: "pocet_spravovanych_bytu",
        label: "Počet spravovaných bytů",
        type: "number",
        required: true,
        reportable: true,
        help: "Klíčový ukazatel velikosti a potenciálu.",
      },
      {
        key: "spolecnosti_vymeny",
        label: "Společnosti, se kterými spolupracují na výměnách",
        type: "multiselect",
        required: true,
        codebook: "dodavatele_vymen",
        multi: true,
        allowOther: true,
        reportable: true,
        help: "Číselník spravuje admin. Možnost více hodnot; pro neuvedené použij „Jiné“.",
      },
      {
        key: "vyhody_nevyhody",
        label: "Výhody, nevýhody služeb a cenová hladina",
        type: "textarea",
        required: false,
        help: "Podklad pro argumentaci a positioning.",
      },
      {
        key: "prumerna_cena_vymeny",
        label: "Průměrná cena výměny",
        type: "currency",
        required: false,
        unit: "Kč",
        reportable: true,
        help: "Strukturované pole pro reporting.",
      },
      {
        key: "podminky_zarazeni",
        label: "Podmínky zařazení Renovy mezi potenciální dodavatele",
        type: "textarea",
        required: true,
        help: "Klíčové pole pro další obchodní postup.",
      },
      {
        key: "system_rozuctovani",
        label: "Jaký systém používají pro rozúčtování",
        type: "tags",
        required: true,
        codebook: "system_rozuctovani",
        multi: true,
        learn: true,
        scored: true,
        reportable: true,
        help: "Vpisuj volně jako tagy — vyber z dříve použitých, nebo napiš nový (uloží se pro příště). Vstup do skóringu.",
      },
      {
        key: "zvyhodneni_nabidek",
        label: "Možnost zvýhodnění nabídek vůči konkurenci",
        type: "textarea",
        required: false,
        help: "Provizní systém nebo jiné obchodní nastavení.",
      },
    ],
  },

  // 8.3 — SVJ
  {
    key: "svj",
    label: "SVJ",
    short: "Společenství vlastníků",
    description: "Společenství vlastníků jednotek — technický detail instalace a měřidel.",
    conditionalRule: "svjMarkOrPhoto",
    fields: [
      {
        key: "pocet_bytu",
        label: "Počet bytů",
        type: "number",
        required: true,
        reportable: true,
        help: "Velikost příležitosti.",
      },
      {
        key: "pocet_meridel",
        label: "Počet měřidel",
        type: "number",
        required: true,
        reportable: true,
        help: "Velikost příležitosti.",
      },
      {
        key: "skladba_meridel",
        label: "Skladba měřidel",
        type: "textarea",
        required: true,
        help: "Podklad pro nabídku.",
      },
      {
        key: "stavebni_delky",
        label: "Stavební délky",
        type: "multiselect",
        required: true,
        codebook: "stavebni_delky",
        multi: true,
        allowOther: true,
        reportable: true,
        help: "Vyber z přednastavených délek; pro jinou použij „Jiné“. Podklad pro technické řešení.",
      },
      {
        key: "znacka_meridel",
        label: "Značka stávajících měřidel",
        type: "multiselect",
        required: "conditional",
        codebook: "znacky_meridel",
        multi: true,
        allowOther: true,
        reportable: true,
        help: "Vyber z číselníku značek; pro neuvedenou „Jiné“. Povinné, pokud není nahraná fotografie.",
      },
      {
        key: "foto_meridel",
        label: "Fotografie stávajících měřidel",
        type: "file",
        required: "conditional",
        help: "Povinné, pokud není vyplněná značka stávajících měřidel.",
      },
      {
        key: "posledni_dodavatel",
        label: "Poslední dodavatel výměny",
        type: "radio",
        required: false,
        codebook: "dodavatele_vymen",
        allowOther: true,
        reportable: true,
        help: "Z číselníku dodavatelů výměn; pro neuvedeného „Jiné“.",
      },
      {
        key: "technologie_odectu",
        label: "Používaná technologie dálkového odečtu",
        type: "radio",
        required: true,
        codebook: "technologie_odectu",
        allowOther: true,
        scored: true,
        reportable: true,
        help: "Vyber technologii; pro neuvedenou „Jiné“. Vstup do skóringu (write-back).",
      },
      {
        key: "specifika_instalace",
        label: "Specifika instalace",
        type: "textarea",
        required: true,
        help: "Kolísání vody, ventily, stáří rozvodů, přívod nebo vratka.",
      },
      {
        key: "kolisani_vody",
        label: "Kolísání vody",
        type: "select",
        required: false,
        options: [
          { value: "zadne", label: "Žádné" },
          { value: "obcasne", label: "Občasné" },
          { value: "caste", label: "Časté" },
        ],
        help: "Strukturované doplnění pro reporting.",
      },
      {
        key: "funkcnost_ventilu",
        label: "Funkčnost ventilů",
        type: "select",
        required: false,
        options: [
          { value: "funkcni", label: "Funkční" },
          { value: "castecne", label: "Částečně funkční" },
          { value: "nefunkcni", label: "Nefunkční" },
        ],
        help: "Strukturované doplnění pro reporting.",
      },
      {
        key: "stari_rozvodu",
        label: "Stáří rozvodů",
        type: "text",
        required: false,
        help: "Text nebo počet let. Strukturované doplnění pro reporting.",
      },
      {
        key: "meridlo_privod_vratka",
        label: "Měřidlo na přívodu nebo vratce",
        type: "select",
        required: false,
        options: [
          { value: "privod", label: "Přívod" },
          { value: "vratka", label: "Vratka" },
          { value: "oboje", label: "Oboje" },
          { value: "zadne", label: "Žádné" },
        ],
        help: "Strukturované doplnění pro reporting.",
      },
      {
        key: "podminky_zarazeni",
        label: "Podmínky zařazení Renovy mezi potenciální dodavatele",
        type: "textarea",
        required: false,
        help: "Obchodní postup.",
      },
      {
        key: "zvyhodneni_nabidek",
        label: "Možnost zvýhodnění nabídek vůči konkurenci",
        type: "textarea",
        required: false,
        help: "Provizní systém nebo jiné obchodní nastavení.",
      },
    ],
  },
];

export function getSegment(key: string): SegmentDef | undefined {
  return SEGMENTS.find((s) => s.key === key);
}
